/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;



import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;

import net.proteanit.sql.DbUtils;
/**
 *
 * 
 */
public class sessions extends javax.swing.JFrame {

    private boolean True;

    private static final String username = "root";
    private static final String password = "";
    private static final String dataConn = "jdbc:mysql://localhost:3306/timetablesystem";

    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form NewJFrame
     */
    public sessions() {
        initComponents();
        displaytable();
        lecCombobox();
        tagCombobox();
        subCombobox();
        
        roomComboBox();
      
        table_update();
        lectureCombo();
        groupCombo();
        subGroupCombo();
        sessionIDCombo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        nb = new javax.swing.JPanel();
        WDH = new javax.swing.JButton();
        lecture = new javax.swing.JButton();
        student = new javax.swing.JButton();
        subject = new javax.swing.JButton();
        tag = new javax.swing.JButton();
        session = new javax.swing.JButton();
        location = new javax.swing.JButton();
        generate = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        stat = new javax.swing.JButton();
        heading = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logo = new javax.swing.JPanel();
        logoLab = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        contnt = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLecture = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSubject = new javax.swing.JComboBox<>();
        jTag = new javax.swing.JComboBox<>();
        jGroup = new javax.swing.JComboBox<>();
        jNoStud = new javax.swing.JTextField();
        jDura = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSession = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLecture2 = new javax.swing.JComboBox<>();
        contnt1 = new javax.swing.JPanel();
        id1 = new javax.swing.JLabel();
        contnt2 = new javax.swing.JPanel();
        id2 = new javax.swing.JLabel();
        contnt3 = new javax.swing.JPanel();
        id3 = new javax.swing.JLabel();
        contnt4 = new javax.swing.JPanel();
        id4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        chkBoxRoom = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        chkBoxDay = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txt_sTime = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_eTime = new javax.swing.JTextField();
        addPreferedSession = new javax.swing.JButton();
        btnClearPreSession = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        contnt5 = new javax.swing.JPanel();
        id5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        chkBoxlec = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        chkBoxGrp = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        chkBoxSubGrp = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        chkBox_sDay = new javax.swing.JComboBox<>();
        btnAddNot_A_T_Session = new javax.swing.JButton();
        BtnClearNAT = new javax.swing.JButton();
        BtnDeleteNAT = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        chkBox_sessionID = new javax.swing.JComboBox<>();
        txt_sTime1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_eTime1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nb.setBackground(new java.awt.Color(153, 153, 255));

        WDH.setText("Working Days and Hours");
        WDH.setPreferredSize(new java.awt.Dimension(131, 30));
        WDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WDHActionPerformed(evt);
            }
        });

        lecture.setText("Lecturers");
        lecture.setPreferredSize(new java.awt.Dimension(131, 30));
        lecture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lectureActionPerformed(evt);
            }
        });

        student.setText("Students");
        student.setPreferredSize(new java.awt.Dimension(131, 30));
        student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentActionPerformed(evt);
            }
        });

        subject.setText("Subjects");
        subject.setPreferredSize(new java.awt.Dimension(131, 30));
        subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectActionPerformed(evt);
            }
        });

        tag.setText("Tags");
        tag.setPreferredSize(new java.awt.Dimension(131, 30));
        tag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagActionPerformed(evt);
            }
        });

        session.setBackground(new java.awt.Color(51, 51, 51));
        session.setText("Sessions");
        session.setPreferredSize(new java.awt.Dimension(131, 30));

        location.setText("Locations");
        location.setPreferredSize(new java.awt.Dimension(131, 30));
        location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationActionPerformed(evt);
            }
        });

        generate.setText("Generate Timetable");
        generate.setPreferredSize(new java.awt.Dimension(131, 30));
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(255, 0, 51));
        logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/logout.png"))); // NOI18N
        logout.setText("LOGOUT");
        logout.setAutoscrolls(true);

        stat.setText("Statistics");
        stat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nbLayout = new javax.swing.GroupLayout(nb);
        nb.setLayout(nbLayout);
        nbLayout.setHorizontalGroup(
            nbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lecture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(WDH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(student, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(subject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(session, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(location, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(generate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(nbLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
            .addComponent(stat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        nbLayout.setVerticalGroup(
            nbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lecture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(session, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout)
                .addContainerGap())
        );

        heading.setBackground(new java.awt.Color(153, 153, 255));
        heading.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("                       TIME TABLE MANAGEMENT SYSTEM");

        javax.swing.GroupLayout headingLayout = new javax.swing.GroupLayout(heading);
        heading.setLayout(headingLayout);
        headingLayout.setHorizontalGroup(
            headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        headingLayout.setVerticalGroup(
            headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        logo.setBackground(new java.awt.Color(153, 153, 255));

        logoLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Hnet.com-image.png"))); // NOI18N

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLab, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoLab))
        );

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jLabel2.setText("Select Lecture");

        jLabel3.setText("Subject code");

        jLabel4.setText("Tag");

        jLabel5.setText("Group ID");

        jLabel6.setText("Student count");

        jLabel7.setText("Duration ");

        jTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTagActionPerformed(evt);
            }
        });

        jNoStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNoStudActionPerformed(evt);
            }
        });

        jLabel8.setText("Hrs");

        TableSession.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Lecture", "Lecture 2", "Tag", "Subject Code", "No. Of Students", "Duration", "Group ID"
            }
        ));
        TableSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSessionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableSession);

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 51, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SESSIONS MANAGEMENT");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));

        jLabel9.setText("Select Assistant Lecture");

        jLecture2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        javax.swing.GroupLayout contntLayout = new javax.swing.GroupLayout(contnt);
        contnt.setLayout(contntLayout);
        contntLayout.setHorizontalGroup(
            contntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contntLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 605, Short.MAX_VALUE))
            .addGroup(contntLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(contntLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contntLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(contntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel9))
                    .addGroup(contntLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(50, 50, 50)))
                .addGroup(contntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contntLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(contntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTag, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLecture, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLecture2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(contntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGroup(contntLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(25, 25, 25)))
                        .addGap(21, 21, 21)
                        .addGroup(contntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jGroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jNoStud, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contntLayout.createSequentialGroup()
                                .addComponent(jDura, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(contntLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButton3)
                        .addGap(159, 159, 159)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(37, 37, 37))))
        );
        contntLayout.setVerticalGroup(
            contntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contntLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLecture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jNoStud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(contntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(contntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLecture2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(contntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Manage Sessions", contnt);

        javax.swing.GroupLayout contnt1Layout = new javax.swing.GroupLayout(contnt1);
        contnt1.setLayout(contnt1Layout);
        contnt1Layout.setHorizontalGroup(
            contnt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contnt1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 605, Short.MAX_VALUE))
        );
        contnt1Layout.setVerticalGroup(
            contnt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contnt1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(id1)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consecutive Sessions", contnt1);

        javax.swing.GroupLayout contnt2Layout = new javax.swing.GroupLayout(contnt2);
        contnt2.setLayout(contnt2Layout);
        contnt2Layout.setHorizontalGroup(
            contnt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contnt2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(id2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 605, Short.MAX_VALUE))
        );
        contnt2Layout.setVerticalGroup(
            contnt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contnt2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(id2)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Non Overlapping Sessions", contnt2);

        javax.swing.GroupLayout contnt3Layout = new javax.swing.GroupLayout(contnt3);
        contnt3.setLayout(contnt3Layout);
        contnt3Layout.setHorizontalGroup(
            contnt3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contnt3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(id3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 605, Short.MAX_VALUE))
        );
        contnt3Layout.setVerticalGroup(
            contnt3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contnt3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(id3)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(" Parallel Sessions", contnt3);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Select Room");

        chkBoxRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Select Day");

        chkBoxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Start Time");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("End Time");

        addPreferedSession.setText("Add Session");
        addPreferedSession.setPreferredSize(new java.awt.Dimension(80, 33));
        addPreferedSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPreferedSessionActionPerformed(evt);
            }
        });

        btnClearPreSession.setText("Clear");
        btnClearPreSession.setPreferredSize(new java.awt.Dimension(80, 33));
        btnClearPreSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearPreSessionActionPerformed(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 51, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Add Preferred Session");
        jLabel22.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));

        javax.swing.GroupLayout contnt4Layout = new javax.swing.GroupLayout(contnt4);
        contnt4.setLayout(contnt4Layout);
        contnt4Layout.setHorizontalGroup(
            contnt4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contnt4Layout.createSequentialGroup()
                .addGroup(contnt4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contnt4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(contnt4Layout.createSequentialGroup()
                        .addGroup(contnt4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contnt4Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(id4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contnt4Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(contnt4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contnt4Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkBoxRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(contnt4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(contnt4Layout.createSequentialGroup()
                                            .addComponent(addPreferedSession, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnClearPreSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(contnt4Layout.createSequentialGroup()
                                            .addGroup(contnt4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel12))
                                            .addGap(29, 29, 29)
                                            .addGroup(contnt4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(chkBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(contnt4Layout.createSequentialGroup()
                                                    .addComponent(txt_sTime, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(53, 53, 53)
                                                    .addComponent(jLabel14)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txt_eTime, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                        .addGap(0, 112, Short.MAX_VALUE)))
                .addContainerGap())
        );
        contnt4Layout.setVerticalGroup(
            contnt4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contnt4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id4)
                .addGap(46, 46, 46)
                .addGroup(contnt4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contnt4Layout.createSequentialGroup()
                        .addGroup(contnt4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(chkBoxRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67))
                    .addGroup(contnt4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addGap(47, 47, 47)
                .addGroup(contnt4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_sTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txt_eTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(contnt4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearPreSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPreferedSession, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );

        jTabbedPane1.addTab("Preferred Session", contnt4);

        jLabel15.setText("Select Lecturer");

        chkBoxlec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        jLabel16.setText("Select Group");

        chkBoxGrp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        jLabel17.setText("Select Sub Group");

        chkBoxSubGrp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        jLabel18.setText("Select Day");

        chkBox_sDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));

        btnAddNot_A_T_Session.setText("Submit");
        btnAddNot_A_T_Session.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNot_A_T_SessionActionPerformed(evt);
            }
        });

        BtnClearNAT.setText("Clear");
        BtnClearNAT.setPreferredSize(new java.awt.Dimension(80, 33));
        BtnClearNAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearNATActionPerformed(evt);
            }
        });

        BtnDeleteNAT.setText("Delete");
        BtnDeleteNAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteNATActionPerformed(evt);
            }
        });

        jLabel19.setText("Select Session ID");

        chkBox_sessionID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        jLabel20.setText("Start Time");

        jLabel21.setText("End Time");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Lecturer", "Student Group", "Sudent Subgroup", "Day", "Session ID", "Start Time", "End Time"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 51, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Not Available Time for Sessions");
        jLabel23.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));

        javax.swing.GroupLayout contnt5Layout = new javax.swing.GroupLayout(contnt5);
        contnt5.setLayout(contnt5Layout);
        contnt5Layout.setHorizontalGroup(
            contnt5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contnt5Layout.createSequentialGroup()
                .addGroup(contnt5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contnt5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(id5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contnt5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contnt5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAddNot_A_T_Session, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(BtnClearNAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(BtnDeleteNAT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(contnt5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contnt5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(contnt5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkBox_sDay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contnt5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(chkBoxSubGrp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkBoxGrp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkBoxlec, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contnt5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(contnt5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_sTime1)
                    .addComponent(txt_eTime1)
                    .addComponent(chkBox_sessionID, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        contnt5Layout.setVerticalGroup(
            contnt5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contnt5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id5)
                .addGap(35, 35, 35)
                .addGroup(contnt5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(chkBoxlec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkBox_sessionID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contnt5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBoxGrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contnt5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBoxSubGrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21)
                    .addComponent(txt_eTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contnt5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBox_sDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(contnt5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDeleteNAT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnClearNAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddNot_A_T_Session, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Not Available Time", contnt5);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    //display table
        private void displaytable(){
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");
            
            String sql = "select * from session";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            TableSession.setModel(DbUtils.resultSetToTableModel(rs));
            
         
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
            
    }
    
    //combobox
    private void lecCombobox(){
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");
            
            String sql = "select * from lecture";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
             while(rs.next()){
                 jLecture.addItem(rs.getString("Name"));
             }
           
            
         
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
            
    }
     private void tagCombobox(){
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");
            
            String sql = "select * from tag";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
             while(rs.next()){
                 jTag.addItem(rs.getString("TagName"));
             }
           
            
         
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
            
    }
     private void subCombobox(){
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");
            
            String sql = "select * from subject";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
             while(rs.next()){
                 jSubject.addItem(rs.getString("code"));
             }
         }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
     }
     
     
    
    private void WDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WDHActionPerformed
     
        workingDaysHours working_DaysHours = new workingDaysHours();
        working_DaysHours.show();
        dispose();
        
        
    }//GEN-LAST:event_WDHActionPerformed

    private void subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectActionPerformed
        subject Subject = new subject();
       Subject.show();
       dispose();     

    }//GEN-LAST:event_subjectActionPerformed

    private void lectureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lectureActionPerformed
        lecture Lecture = new lecture();
       Lecture.show();
       dispose();    
    }//GEN-LAST:event_lectureActionPerformed

    private void jTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTagActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");

            String sql = "select * from student";
             String sql2 = "select * from lecture";

            PreparedStatement pst = conn.prepareStatement(sql);
            PreparedStatement pst2 = conn.prepareStatement(sql2);
             
            ResultSet rs = pst.executeQuery();
            ResultSet rs2 = pst2.executeQuery();
            
            jGroup.removeAllItems();
            while(rs.next() & rs2.next()){
                if(jTag.getSelectedItem().equals("Lec") || jTag.getSelectedItem().equals("Tute")){

                    jGroup.addItem(rs.getString("GroupID"));
                    ///////////////
                   // while(rs2.next()){
                 jLecture2.addItem(rs2.getString("Name"));
            // }
                    
                    
                    
                    /////////////

                }else if(jTag.getSelectedItem().equals("Lab")){

                    jGroup.addItem(rs.getString("SubGroupID"));

                }else{
                    jGroup.setSelectedIndex(-1);
                }
            }

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jTagActionPerformed

    private void jNoStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNoStudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNoStudActionPerformed

    private void TableSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSessionMouseClicked
        int i = TableSession.getSelectedRow();
        TableModel model = TableSession.getModel();
        //	lecture	 tag	noOFStudents	groupID	subjectCode	duration
        //issue tag GroupID
        //id.setText(model.getValueAt(i,6).toString());
        String Lec = model.getValueAt(i,1).toString();
        jLecture.setSelectedItem(Lec);
        
        String Lec2 = model.getValueAt(i,2).toString();
        jLecture2.setSelectedItem(Lec2);

        String tags = model.getValueAt(i,3).toString();
        jTag.setSelectedItem(tags);

        jNoStud.setText(model.getValueAt(i,4).toString());

        String groupID = model.getValueAt(i,5).toString();
        jGroup.setSelectedItem(groupID);

        String subjectCode = model.getValueAt(i,6).toString();
        jSubject.setSelectedItem(subjectCode);

        jDura.setText(model.getValueAt(i,7).toString());
    }//GEN-LAST:event_TableSessionMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");

            String sql = "insert into session values (null, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            //	lecture	 tag	noOFStudents	groupID	subjectCode	duration

            String lec;
            lec = jLecture.getSelectedItem().toString();
            pst.setString(1, lec);
            
            String lec2;
            lec2 = jLecture2.getSelectedItem().toString();
            pst.setString(2, lec2);

            String tag;
            tag = jTag.getSelectedItem().toString();
            pst.setString(3, tag);

            try{
                pst.setInt(4, Integer.parseInt(jNoStud.getText()));

            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Invalid Input : enter a valid number for No OF Students");
            }

            String groupID;
            groupID = jGroup.getSelectedItem().toString();
            pst.setString(5, groupID);

            String subjectCode;
            subjectCode = jSubject.getSelectedItem().toString();
            pst.setString(6, subjectCode);

            try{
                pst.setInt(7, Integer.parseInt(jDura.getText()));

            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Invalid Input : enter a valid number for Duration");
            }

            pst.executeUpdate();

            //refresh table after insert data
            DefaultTableModel model = (DefaultTableModel)TableSession.getModel();
            model.setRowCount(0);
            displaytable();

            JOptionPane.showMessageDialog(this, "Session added");

            conn.close();

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }

        }

        private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");

            int row = TableSession.getSelectedRow();
            String value = (TableSession.getModel().getValueAt(row, 0).toString());
            String query = "DELETE FROM session WHERE id="+value;
            PreparedStatement pst = conn.prepareStatement(query);
            pst.executeUpdate();

            DefaultTableModel model = (DefaultTableModel)TableSession.getModel();
            model.setRowCount(0);
            displaytable();

            JOptionPane.showMessageDialog(this, "Session deleted");
            conn.close();

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");
            //	lecture	 tag	noOFStudents	groupID	subjectCode	duration
            String sql = "Update session set   lecture = ?, lecture2 = ?, tag = ? , noOFStudents = ?, groupID = ?, subjectCode = ? , durationHrs = ?  where id = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, jLecture.getSelectedItem().toString());
            pstmt.setString(2, jLecture2.getSelectedItem().toString());
            pstmt.setString(3, jTag.getSelectedItem().toString());
            pstmt.setString(4, jNoStud.getText());
            pstmt.setString(5, jGroup.getSelectedItem().toString());
            pstmt.setString(6, jSubject.getSelectedItem().toString());
            pstmt.setString(7, jDura.getText());

            int row = TableSession.getSelectedRow();
            String id = (TableSession.getModel().getValueAt(row, 0).toString());
            pstmt.setString(8, id);

            //to disable for editing  the TagID field

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Session updated succussfully");

            DefaultTableModel model = (DefaultTableModel)TableSession.getModel();
            model.setRowCount(0);
            displaytable();

            jLecture.setSelectedIndex(0);
            jTag.setSelectedIndex(0);
            jNoStud.setText("");
            jGroup.setSelectedIndex(0);
            jSubject.setSelectedIndex(0);
            jDura.setText("");

            conn.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

        //refresh table after insert data
        DefaultTableModel model = (DefaultTableModel)TableSession.getModel();
        model.setRowCount(0);
        displaytable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jLecture.setSelectedIndex(0);
        jTag.setSelectedIndex(0);
        jNoStud.setText("");
        jGroup.setSelectedIndex(0);
        jSubject.setSelectedIndex(0);
        jDura.setText("");
        id.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentActionPerformed
        // TODO add your handling code here:
        Students stud = new Students();
       stud.show();
       dispose();
    }//GEN-LAST:event_studentActionPerformed

    private void tagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagActionPerformed
        // TODO add your handling code here:
        Tags tags = new Tags();
        tags.show();
        dispose();
    }//GEN-LAST:event_tagActionPerformed

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        // TODO add your handling code here:
        AddLocation locatn = new AddLocation();
        locatn.show();
        dispose();
    }//GEN-LAST:event_locationActionPerformed

    private void statActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statActionPerformed
        // TODO add your handling code here:
         Statistics stats = new Statistics();
        stats.show();
        dispose();
    }//GEN-LAST:event_statActionPerformed

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        // TODO add your handling code here:
         generateTimetable genTime = new generateTimetable();
        genTime.show();
        dispose();
    }//GEN-LAST:event_generateActionPerformed

    
    
    
    private void addPreferedSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPreferedSessionActionPerformed

        String sRoom = chkBoxRoom.getSelectedItem().toString();
        String sDay = chkBoxDay.getSelectedItem().toString();
//        String sTime = txt_sTime.getText();
//        String eTime = txt_eTime.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");

            pst = sqlConn.prepareStatement("insert into addpreferredsession(selectRoom, selectDay, startTime, endTime)values(?,?,?,?)");

            try{
                pst.setInt(3, Integer.parseInt(txt_sTime.getText()));

            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Invalid Input : enter a valid Time");
            }
            
            try{
                pst.setInt(4, Integer.parseInt(txt_eTime.getText()));

            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Invalid Input : enter a valid Time");
            }
            
            pst.setString(1, sRoom);
            pst.setString(2, sDay);
//            pst.setString(3, sTime);
//            pst.setString(4, eTime);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Successfully added!!!");

       }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_addPreferedSessionActionPerformed

    private void btnClearPreSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearPreSessionActionPerformed
        chkBoxRoom.setSelectedIndex(0);
        chkBoxDay.setSelectedIndex(0);
        txt_sTime.setText("");
        txt_eTime.setText("");
    }//GEN-LAST:event_btnClearPreSessionActionPerformed

    
    
    private void table_update()
    {
        int c;
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");
            
            pst = sqlConn.prepareStatement("select * from addnotavailabletimesession");
            java.sql.ResultSet rs = pst.executeQuery();
            ResultSetMetaData Rss = rs.getMetaData();
            c = Rss.getColumnCount();
            
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            
            model.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2 = new Vector(); 
                
                for(int a=1; a<=c; a++)
                {
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("sLecturer"));
                    v2.add(rs.getString("sGroup"));
                    v2.add(rs.getString("sSub_Group"));
                    v2.add(rs.getString("sDay"));
                    v2.add(rs.getString("sSessionID"));
                    v2.add(rs.getString("startTime"));
                    v2.add(rs.getString("endTime"));
                }
                
                model.addRow(v2);
                
            }
            
   
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(workingDaysHours.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(workingDaysHours.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btnAddNot_A_T_SessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNot_A_T_SessionActionPerformed
       
        
        String sLecturer = chkBoxlec.getSelectedItem().toString();
        String sGroup = chkBoxGrp.getSelectedItem().toString();
        String sSubgroup = chkBoxSubGrp.getSelectedItem().toString();
        String sDay = chkBox_sDay.getSelectedItem().toString();
        String s_sessionID = chkBox_sessionID.getSelectedItem().toString();
//        String sTime = txt_sTime1.getText();
//        String eTime = txt_eTime1.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");

            pst = sqlConn.prepareStatement("insert into addnotavailabletimesession(sLecturer, sGroup, sSub_Group, sDay, sSessionID, startTime, endTime)values(?,?,?,?,?,?,?)");

            try{
                pst.setInt(6, Integer.parseInt(txt_sTime1.getText()));

            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Invalid Input : enter a valid Time");
            }
            
            try{
                pst.setInt(7, Integer.parseInt(txt_eTime1.getText()));

            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Invalid Input : enter a valid Time");
            }
            
            pst.setString(1, sLecturer);
            pst.setString(2, sGroup);
            pst.setString(3, sSubgroup);
            pst.setString(4, sDay);
            pst.setString(5, s_sessionID);
//            pst.setString(6, sTime);
//            pst.setString(7, eTime);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Successfully added!!!");
            table_update();

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnAddNot_A_T_SessionActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int i = jTable1.getSelectedRow();
        
        String lect = model.getValueAt(i,1).toString();
        chkBoxlec.setSelectedItem(lect);
        
        String grp = model.getValueAt(i,2).toString();
        chkBoxGrp.setSelectedItem(grp);
        
        String sgrp = model.getValueAt(i,3).toString();
        chkBoxSubGrp.setSelectedItem(sgrp);
        
        String sday = model.getValueAt(i,4).toString();
        chkBox_sDay.setSelectedItem(sday);
        
        String sesid = model.getValueAt(i,5).toString();
        chkBox_sessionID.setSelectedItem(sesid);
        

        txt_sTime1.setText(model.getValueAt(i, 6).toString());
        txt_eTime1.setText(model.getValueAt(i, 7).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void BtnClearNATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearNATActionPerformed
        
        chkBoxlec.setSelectedIndex(0);
        chkBoxGrp.setSelectedIndex(0);
        chkBoxSubGrp.setSelectedIndex(0);
        chkBox_sDay.setSelectedIndex(0);
        chkBox_sessionID.setSelectedIndex(0);
        txt_sTime1.setText("");
        txt_eTime1.setText("");
        
    }//GEN-LAST:event_BtnClearNATActionPerformed

    private void BtnDeleteNATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteNATActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int i = jTable1.getSelectedRow();
         
         try {
             int id = Integer.parseInt(model.getValueAt(i, 0).toString());
             
             int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to delete the record?","Warning",JOptionPane.YES_NO_OPTION);
             
             if(dialogResult == JOptionPane.YES_OPTION){
                 
                 Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");
            
            pst = sqlConn.prepareStatement("delete from addnotavailabletimesession where id=? ");
            
        
            pst.setInt(1, id);
                 
            
            pst.executeUpdate();
            
            
            JOptionPane.showMessageDialog(this, "Successfully Deleted!!!");
            table_update();
            
            chkBoxlec.setSelectedIndex(0);
        chkBoxGrp.setSelectedIndex(0);
        chkBoxSubGrp.setSelectedIndex(0);
        chkBox_sDay.setSelectedIndex(0);
        chkBox_sessionID.setSelectedIndex(0);
        txt_sTime1.setText("");
        txt_eTime1.setText("");
            
             }
     
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(workingDaysHours.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(workingDaysHours.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnDeleteNATActionPerformed

    private void roomComboBox(){
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");
            
            String sql = "select * from location";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
             while(rs.next()){
                 chkBoxRoom.addItem(rs.getString("room"));
             }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
            
    }
    
    
    
    private void lectureCombo(){
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");
            
            String sql = "select * from lecture";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
             while(rs.next()){
                 chkBoxlec.addItem(rs.getString("Name"));
             }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
            
    }
    private void groupCombo(){
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");
            
            String sql = "select * from student";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
             while(rs.next()){
                 chkBoxGrp.addItem(rs.getString("GroupID"));
             }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
            
    }
    private void subGroupCombo(){
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");
            
            String sql = "select * from student";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
             while(rs.next()){
                 chkBoxSubGrp.addItem(rs.getString("SubGroupID"));
             }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
            
    }
    private void sessionIDCombo(){
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");
            
            String sql = "select * from session";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
             while(rs.next()){
                 chkBox_sessionID.addItem(rs.getString("id"));
             }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
            
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sessions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sessions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sessions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sessions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sessions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClearNAT;
    private javax.swing.JButton BtnDeleteNAT;
    private javax.swing.JTable TableSession;
    private javax.swing.JButton WDH;
    private javax.swing.JButton addPreferedSession;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnAddNot_A_T_Session;
    private javax.swing.JButton btnClearPreSession;
    private javax.swing.JComboBox<String> chkBoxDay;
    private javax.swing.JComboBox<String> chkBoxGrp;
    private javax.swing.JComboBox<String> chkBoxRoom;
    private javax.swing.JComboBox<String> chkBoxSubGrp;
    private javax.swing.JComboBox<String> chkBox_sDay;
    private javax.swing.JComboBox<String> chkBox_sessionID;
    private javax.swing.JComboBox<String> chkBoxlec;
    private javax.swing.JPanel contnt;
    private javax.swing.JPanel contnt1;
    private javax.swing.JPanel contnt2;
    private javax.swing.JPanel contnt3;
    private javax.swing.JPanel contnt4;
    private javax.swing.JPanel contnt5;
    private javax.swing.JButton generate;
    private javax.swing.JPanel heading;
    private javax.swing.JLabel id;
    private javax.swing.JLabel id1;
    private javax.swing.JLabel id2;
    private javax.swing.JLabel id3;
    private javax.swing.JLabel id4;
    private javax.swing.JLabel id5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JTextField jDura;
    private javax.swing.JComboBox<String> jGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jLecture;
    private javax.swing.JComboBox<String> jLecture2;
    private javax.swing.JTextField jNoStud;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jSubject;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jTag;
    private javax.swing.JButton lecture;
    private javax.swing.JButton location;
    private javax.swing.JPanel logo;
    private javax.swing.JLabel logoLab;
    private javax.swing.JButton logout;
    private javax.swing.JPanel nb;
    private javax.swing.JButton session;
    private javax.swing.JButton stat;
    private javax.swing.JButton student;
    private javax.swing.JButton subject;
    private javax.swing.JButton tag;
    private javax.swing.JTextField txt_eTime;
    private javax.swing.JTextField txt_eTime1;
    private javax.swing.JTextField txt_sTime;
    private javax.swing.JTextField txt_sTime1;
    // End of variables declaration//GEN-END:variables
}
