package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Noha Menani
 */


// creating jframe for student details and management

public class Students extends javax.swing.JFrame {
    
   
   private boolean True;

    /**
     * Creates new form NewJFrame
     */
    public Students() {
        initComponents();
        DisplayStudent();
    }

    private void DisplayStudent(){
        
        // displaying students details
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");
            
            String sql = "select * from student";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            
            studentTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        nb = new javax.swing.JPanel();
        WDH = new javax.swing.JButton();
        lecture = new javax.swing.JButton();
        student = new javax.swing.JButton();
        subject = new javax.swing.JButton();
        tag = new javax.swing.JButton();
        session = new javax.swing.JButton();
        location = new javax.swing.JButton();
        generate = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        stat = new javax.swing.JButton();
        heading = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logo = new javax.swing.JPanel();
        logoLab = new javax.swing.JLabel();
        contnt = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Programmefield = new javax.swing.JComboBox<>();
        generateIDbtn = new javax.swing.JButton();
        GroupIDfield = new javax.swing.JTextField();
        SubGroupIDfield = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        AddStudentBtn = new javax.swing.JButton();
        GroupNoField = new javax.swing.JTextField();
        SubGroupNoField = new javax.swing.JTextField();
        EmptyMsg3Lbl = new javax.swing.JLabel();
        AYSerrorLabel = new javax.swing.JLabel();
        AYSfield = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        EditProgrammeField = new javax.swing.JComboBox<>();
        generateID2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        EditGroupIDField = new javax.swing.JTextField();
        EditSubGroupIDField = new javax.swing.JTextField();
        Clear = new javax.swing.JButton();
        UpdateStudentButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        StudentIDField = new javax.swing.JTextField();
        EditGroupNoField = new javax.swing.JTextField();
        EditSubGroupNoField = new javax.swing.JTextField();
        EmptyMsg4Lbl = new javax.swing.JLabel();
        DeleteStudentButton = new javax.swing.JButton();
        EditAYSfield = new javax.swing.JComboBox<>();
        errorlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Victory Institute - Student Groups");
        setBounds(new java.awt.Rectangle(50, 50, 50, 50));
        setLocation(new java.awt.Point(50, 300));
        setUndecorated(true);

        nb.setBackground(new java.awt.Color(153, 153, 255));

        WDH.setText("Working Days and Hours");
        WDH.setPreferredSize(new java.awt.Dimension(131, 30));
        WDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WDHActionPerformed(evt);
            }
        });

        lecture.setText("Lecturers");
        lecture.setPreferredSize(new java.awt.Dimension(131, 30));
        lecture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lectureActionPerformed(evt);
            }
        });

        student.setBackground(new java.awt.Color(153, 153, 153));
        student.setText("Students");
        student.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        student.setPreferredSize(new java.awt.Dimension(131, 30));
        student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentActionPerformed(evt);
            }
        });

        subject.setText("Subjects");
        subject.setPreferredSize(new java.awt.Dimension(131, 30));
        subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectActionPerformed(evt);
            }
        });

        tag.setText("Tags");
        tag.setPreferredSize(new java.awt.Dimension(131, 30));
        tag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagActionPerformed(evt);
            }
        });

        session.setText("Sessions");
        session.setPreferredSize(new java.awt.Dimension(131, 30));
        session.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sessionActionPerformed(evt);
            }
        });

        location.setText("Locations");
        location.setPreferredSize(new java.awt.Dimension(131, 30));
        location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationActionPerformed(evt);
            }
        });

        generate.setText("Generate Timetable");
        generate.setPreferredSize(new java.awt.Dimension(131, 30));
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/shutdown (1).png"))); // NOI18N
        logout.setText("Exit");
        logout.setAutoscrolls(true);
        logout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 4, true));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        stat.setText("Statistics");
        stat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nbLayout = new javax.swing.GroupLayout(nb);
        nb.setLayout(nbLayout);
        nbLayout.setHorizontalGroup(
            nbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lecture, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
            .addComponent(WDH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(student, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(subject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(session, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(location, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(generate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(stat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(nbLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nbLayout.setVerticalGroup(
            nbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lecture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(session, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        heading.setBackground(new java.awt.Color(153, 153, 255));
        heading.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("                       TIME TABLE MANAGEMENT SYSTEM");

        javax.swing.GroupLayout headingLayout = new javax.swing.GroupLayout(heading);
        heading.setLayout(headingLayout);
        headingLayout.setHorizontalGroup(
            headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        headingLayout.setVerticalGroup(
            headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        logo.setBackground(new java.awt.Color(153, 153, 255));

        logoLab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Hnet.com-image.png"))); // NOI18N

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLab, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoLab))
        );

        jTabbedPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));

        jLabel2.setText("Academic Year and Semester");

        jLabel3.setText("Programme");

        jLabel4.setText("Group Number");

        jLabel5.setText("Sub Group Number");

        jLabel6.setText("Group ID");

        jLabel7.setText("Sub Group ID");

        Programmefield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "IT", "CSSE", "CSE", "IM" }));
        Programmefield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProgrammefieldMouseClicked(evt);
            }
        });

        generateIDbtn.setForeground(new java.awt.Color(255, 0, 0));
        generateIDbtn.setText("Click to Generate IDs");
        generateIDbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        generateIDbtn.setPreferredSize(new java.awt.Dimension(105, 30));
        generateIDbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateIDbtnActionPerformed(evt);
            }
        });

        GroupIDfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GroupIDfieldActionPerformed(evt);
            }
        });
        GroupIDfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                GroupIDfieldKeyReleased(evt);
            }
        });

        SubGroupIDfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SubGroupIDfieldKeyReleased(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Button-Delete-icon_1_20x20.png"))); // NOI18N
        jButton2.setText("Clear");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        jButton2.setPreferredSize(new java.awt.Dimension(69, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        AddStudentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/icons8-insert-button-48 (1).png"))); // NOI18N
        AddStudentBtn.setText("Add");
        AddStudentBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        AddStudentBtn.setPreferredSize(new java.awt.Dimension(69, 30));
        AddStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentBtnActionPerformed(evt);
            }
        });

        GroupNoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                GroupNoFieldKeyReleased(evt);
            }
        });

        SubGroupNoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SubGroupNoFieldKeyReleased(evt);
            }
        });

        EmptyMsg3Lbl.setForeground(new java.awt.Color(204, 0, 0));

        AYSfield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Y1.S1", "Y1.S2", "Y2.S1", "Y2.S2", "Y3.S1", "Y3.S2", "Y4.S1", "Y4.S2" }));
        AYSfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AYSfieldMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(AddStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Programmefield, javax.swing.GroupLayout.Alignment.LEADING, 0, 223, Short.MAX_VALUE)
                                .addComponent(GroupIDfield, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SubGroupIDfield, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(GroupNoField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SubGroupNoField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EmptyMsg3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AYSfield, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(AYSerrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(generateIDbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(EmptyMsg3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AYSerrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AYSfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Programmefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(GroupNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SubGroupNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(generateIDbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(GroupIDfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(SubGroupIDfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jTabbedPane3.addTab("Add Student Group", jPanel2);

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "StudentGID", "Academic Year ans Semester", "Programme", "Group Number", "Group ID", "Sub Group Number", "Sub Group ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Short.class, java.lang.String.class, java.lang.Short.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentTable.setGridColor(new java.awt.Color(0, 0, 255));
        studentTable.setRowHeight(25);
        studentTable.setSelectionBackground(new java.awt.Color(102, 102, 255));
        studentTable.setShowGrid(true);
        studentTable.setShowVerticalLines(false);
        studentTable.getTableHeader().setReorderingAllowed(false);
        studentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentTable);

        jLabel8.setText("Academic Year and Semester");

        jLabel9.setText("Programme");

        jLabel10.setText("Group Number");

        jLabel11.setText("Sub Group Number");

        EditProgrammeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "IT", "CSSE", "CSE", "IM" }));
        EditProgrammeField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditProgrammeFieldMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                EditProgrammeFieldMouseReleased(evt);
            }
        });
        EditProgrammeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EditProgrammeFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EditProgrammeFieldKeyReleased(evt);
            }
        });

        generateID2.setForeground(new java.awt.Color(255, 0, 0));
        generateID2.setText("Click to generate IDs");
        generateID2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        generateID2.setPreferredSize(new java.awt.Dimension(105, 30));
        generateID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateID2ActionPerformed(evt);
            }
        });

        jLabel12.setText("Group ID");

        jLabel13.setText("Sub Group ID");

        EditGroupIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditGroupIDFieldActionPerformed(evt);
            }
        });

        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Button-Delete-icon_1_20x20.png"))); // NOI18N
        Clear.setText("Clear");
        Clear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        Clear.setPreferredSize(new java.awt.Dimension(69, 30));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        UpdateStudentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Apps-system-software-update-icon_24x24.png"))); // NOI18N
        UpdateStudentButton.setText("Update");
        UpdateStudentButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        UpdateStudentButton.setPreferredSize(new java.awt.Dimension(69, 30));
        UpdateStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateStudentButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("StudentGID");

        StudentIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentIDFieldActionPerformed(evt);
            }
        });

        EditGroupNoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EditGroupNoFieldKeyReleased(evt);
            }
        });

        EditSubGroupNoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EditSubGroupNoFieldKeyReleased(evt);
            }
        });

        EmptyMsg4Lbl.setForeground(new java.awt.Color(204, 0, 0));

        DeleteStudentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/delete.png"))); // NOI18N
        DeleteStudentButton.setText("Delete Student Group");
        DeleteStudentButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 3, true));
        DeleteStudentButton.setPreferredSize(new java.awt.Dimension(69, 30));
        DeleteStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteStudentButtonActionPerformed(evt);
            }
        });

        EditAYSfield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Y1.S1", "Y1.S2", "Y2.S1", "Y2.S2", "Y3.S1", "Y3.S2", "Y4.S1", "Y4.S2" }));
        EditAYSfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditAYSfieldMouseClicked(evt);
            }
        });
        EditAYSfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EditAYSfieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EditAYSfieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EditAYSfieldKeyTyped(evt);
            }
        });

        errorlabel.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(DeleteStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EditAYSfield, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11))
                                .addGap(94, 94, 94)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EditProgrammeField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EditGroupNoField)
                                    .addComponent(EditSubGroupNoField)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(StudentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(EditGroupIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(EditSubGroupIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(4, 14, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 125, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Clear, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                            .addComponent(UpdateStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(generateID2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(EmptyMsg4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(errorlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(DeleteStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(EmptyMsg4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(StudentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(UpdateStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EditAYSfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EditProgrammeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(generateID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(EditGroupNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(EditGroupIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(EditSubGroupIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(EditSubGroupNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54)
                .addComponent(errorlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Manage Student Group", jPanel3);

        javax.swing.GroupLayout contntLayout = new javax.swing.GroupLayout(contnt);
        contnt.setLayout(contntLayout);
        contntLayout.setHorizontalGroup(
            contntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contntLayout.createSequentialGroup()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        contntLayout.setVerticalGroup(
            contntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void WDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WDHActionPerformed
       workingDaysHours working_DaysHours = new workingDaysHours();
        working_DaysHours.show();
        dispose();
    }//GEN-LAST:event_WDHActionPerformed
    
    private void studentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentTableMouseClicked
        
        // disable editing student ID
        StudentIDField.setEditable(false);
        
        //fetching student data from jtable to form
        
        DefaultTableModel model = (DefaultTableModel)studentTable.getModel();
        int selectedRowIndex = studentTable.getSelectedRow();
        
        StudentIDField.setText(model.getValueAt(selectedRowIndex, 0).toString()); // Student Group ID
        
        String AYSCombo = model.getValueAt(selectedRowIndex, 1).toString();     //Academic Year and Semester
        for(int i = 0; i < EditAYSfield.getItemCount(); i ++){
        if (EditAYSfield.getItemAt(i).toString().equalsIgnoreCase(AYSCombo)){
            EditAYSfield.setSelectedIndex(i);
            }
        }
        
        String ProgrammeCombo = model.getValueAt(selectedRowIndex, 2).toString(); //Programme
        for(int i = 0; i < EditProgrammeField.getItemCount(); i ++){
        if (EditProgrammeField.getItemAt(i).toString().equalsIgnoreCase(ProgrammeCombo)){
            EditProgrammeField.setSelectedIndex(i);
            }
        }
        
        
        EditGroupNoField.setText(model.getValueAt(selectedRowIndex, 3).toString());     //Group Number
        EditSubGroupNoField.setText(model.getValueAt(selectedRowIndex, 4).toString());  //SubGroup Number
        EditGroupIDField.setText(model.getValueAt(selectedRowIndex, 5).toString());     //GroupID
        EditSubGroupIDField.setText(model.getValueAt(selectedRowIndex, 6).toString());  //SubGroupID
    }//GEN-LAST:event_studentTableMouseClicked

    private void generateID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateID2ActionPerformed
        if(EditAYSfield.getSelectedItem().toString().equalsIgnoreCase("") || EditProgrammeField.getSelectedItem().toString().equalsIgnoreCase("") || EditGroupNoField.getText().trim().equalsIgnoreCase("") ||  EditSubGroupNoField.getText().trim().equalsIgnoreCase("")  ){
            errorlabel.setText("Please fill all the details ");
        }
        else{
        EditGroupIDField.setText(EditAYSfield.getSelectedItem()+ "." + EditProgrammeField.getSelectedItem() + "." + EditGroupNoField.getText());
        EditSubGroupIDField.setText(EditAYSfield.getSelectedItem()+ "." + EditProgrammeField.getSelectedItem() + "." + EditGroupNoField.getText() + "." + EditSubGroupNoField.getText() );
        }  
        EmptyMsg4Lbl.setText("");
        
    }//GEN-LAST:event_generateID2ActionPerformed

    private void UpdateStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateStudentButtonActionPerformed
         
        // disable editing
        StudentIDField.setEditable(false);
        
        
        if(StudentIDField.getText().trim().isEmpty() ||  EditAYSfield.getSelectedItem().toString().isEmpty() ||  EditProgrammeField.getSelectedItem().toString().isEmpty() || EditGroupNoField.getText().trim().isEmpty() || EditSubGroupNoField.getText().trim().isEmpty() || EditGroupIDField.getText().trim().isEmpty() || EditSubGroupIDField.getText().trim().isEmpty() ){
            EmptyMsg4Lbl.setText("Please fill all the details ");
        }
        else{ 
            
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");

                //Updating Student data to database
                String sql = "Update student set  AcademicYearSemester = ?, Programme = ?, GroupNo = ?, SubGroupNo = ?,GroupID = ?,SubGroupID = ? where StudentsID = ?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, EditAYSfield.getSelectedItem().toString());
                pstmt.setString(2, EditProgrammeField.getSelectedItem().toString());
                pstmt.setInt(3,Integer.parseInt(EditGroupNoField.getText()));
                pstmt.setInt(4,Integer.parseInt(EditSubGroupNoField.getText()));
                pstmt.setString(5, EditGroupIDField.getText());
                pstmt.setString(6, EditSubGroupIDField.getText());
                pstmt.setInt(7,Integer.parseInt(StudentIDField.getText()));

                //to disable for editing  the StudentGID field
                StudentIDField.setEditable(false);
                
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Student details updated succussfully"); 
                
                
                // after updating ,clearing data in form 
                StudentIDField.setText("");
                EditAYSfield.setSelectedIndex(0);
                EditProgrammeField.setSelectedIndex(0);
                EditGroupNoField.setText(""); 
                EditSubGroupNoField.setText("");
                EditGroupIDField.setText("");
                EditSubGroupIDField.setText("");
                StudentIDField.setText("");
                EditSubGroupNoField.setText("");
                errorlabel.setText("");
                
                conn.close();
                
             }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }



            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");
                
                //Selecting updated data from database to Student Table
                PreparedStatement pstmt = conn.prepareStatement("select * from student");       
                ResultSet rs = pstmt.executeQuery();

                DefaultTableModel tm=(DefaultTableModel)studentTable.getModel();
                tm.setRowCount(0);

                while (rs.next()){
                    Object o[] = {rs.getInt("StudentsID"),rs.getString("AcademicYearSemester"),rs.getString("Programme"),rs.getString("GroupNo"),rs.getString("SubGroupNo"),rs.getString("GroupID"),rs.getString("SubGroupID")};
                    tm.addRow(o);
                }

            } catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_UpdateStudentButtonActionPerformed

    private void DeleteStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteStudentButtonActionPerformed
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");
           
           //deleting students data in database
           String sql = "delete from student where StudentsID = ?";
           PreparedStatement pstmt = conn.prepareStatement(sql);
           pstmt.setInt(1, Integer.parseInt(StudentIDField.getText()));
           pstmt.executeUpdate();
           JOptionPane.showMessageDialog(null, "Student details deleted successfully");
           conn.close();
           
       }catch (Exception e){
       JOptionPane.showMessageDialog(null, e);
       }
       
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");
            
            //Selecting updated data from database to Student Table
            PreparedStatement pstmt = conn.prepareStatement("select * from student");       
            ResultSet rs = pstmt.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)studentTable.getModel();
            tm.setRowCount(0);
            
            while (rs.next()){
                Object o[] = {rs.getInt("StudentsID"),rs.getString("AcademicYearSemester"),rs.getString("Programme"),rs.getString("GroupNo"),rs.getString("SubGroupNo"),rs.getString("GroupID"),rs.getString("SubGroupID")};
                tm.addRow(o);
            }
           
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
            // after deleting ,clearing data in form
            StudentIDField.setText("");
            EditAYSfield.setSelectedIndex(0);
            EditProgrammeField.setSelectedIndex(0);
            EditGroupNoField.setText(""); 
            EditSubGroupNoField.setText("");
            EditGroupIDField.setText("");
            EditSubGroupIDField.setText("");
            StudentIDField.setText("");
            EditSubGroupNoField.setText("");
    }//GEN-LAST:event_DeleteStudentButtonActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
            StudentIDField.setText("");
            EditAYSfield.setSelectedIndex(0);
            EditProgrammeField.setSelectedIndex(0);
            EditGroupNoField.setText(""); 
            EditSubGroupNoField.setText("");
            EditGroupIDField.setText("");
            EditSubGroupIDField.setText("");
            StudentIDField.setText("");
            EditSubGroupNoField.setText("");
            EmptyMsg4Lbl.setText("");
            errorlabel.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void tagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagActionPerformed
        Tags tags = new Tags();
        tags.show();
        dispose();
    }//GEN-LAST:event_tagActionPerformed

    private void SubGroupNoFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SubGroupNoFieldKeyReleased
        EmptyMsg3Lbl.setText("");
        GroupIDfield.setText("");
        SubGroupIDfield.setText("");
    }//GEN-LAST:event_SubGroupNoFieldKeyReleased

    private void GroupNoFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GroupNoFieldKeyReleased
        EmptyMsg3Lbl.setText("");
        GroupIDfield.setText("");
        SubGroupIDfield.setText("");
    }//GEN-LAST:event_GroupNoFieldKeyReleased

    private void AddStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentBtnActionPerformed
       
        // Validation...
        if(AYSfield.getSelectedItem().toString().isEmpty() ||  Programmefield.getSelectedItem().toString().isEmpty() ||  GroupNoField.getText().trim().isEmpty() ||  SubGroupNoField.getText().trim().isEmpty() || GroupIDfield.getText().trim().isEmpty() ||  SubGroupIDfield.getText().trim().isEmpty()){
            EmptyMsg3Lbl.setText("Please fill all the details ");
            GroupIDfield.setText("");
            SubGroupIDfield.setText("");
        }
        else{
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");

                //adding student data to database
                String sql = "insert into student(AcademicYearSemester,Programme,GroupNo,SubGroupNo,GroupID,SubGroupID) values (?,?,?,?,?,?)";
                PreparedStatement pstmt = conn.prepareStatement(sql);

                pstmt.setString(1, AYSfield.getSelectedItem().toString());
                pstmt.setString(2, Programmefield.getSelectedItem().toString());
                pstmt.setInt(3, Integer.parseInt(GroupNoField.getText()));
                pstmt.setInt(4, Integer.parseInt(SubGroupNoField.getText()));
                pstmt.setString(5, GroupIDfield.getText());
                pstmt.setString(6, SubGroupIDfield.getText());

                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Student details added Successfully");
                conn.close();

                // clear data after adding to database
                AYSfield.setSelectedItem("");
                Programmefield.setSelectedItem("");
                GroupNoField.setText("");
                SubGroupNoField.setText("");
                GroupIDfield.setText("");
                SubGroupIDfield.setText("");

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetablesystem","root","");
            
            //Selecting updated data from database to Student Table after adding
            PreparedStatement pstmt = conn.prepareStatement("select * from student");
            ResultSet rs = pstmt.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)studentTable.getModel();
            tm.setRowCount(0);

            while (rs.next()){
                Object o[] = {rs.getInt("StudentsID"),rs.getString("AcademicYearSemester"),rs.getString("Programme"),rs.getString("GroupNo"),rs.getString("SubGroupNo"),rs.getString("GroupID"),rs.getString("SubGroupID")};
                tm.addRow(o);
            }

        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_AddStudentBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AYSfield.setSelectedIndex(0);
        Programmefield.setSelectedIndex(0);
        GroupNoField.setText("");
        SubGroupNoField.setText("");
        GroupIDfield.setText("");
        SubGroupIDfield.setText("");
        EmptyMsg3Lbl.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void SubGroupIDfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SubGroupIDfieldKeyReleased
        EmptyMsg3Lbl.setText("");
    }//GEN-LAST:event_SubGroupIDfieldKeyReleased

    private void GroupIDfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GroupIDfieldKeyReleased
        EmptyMsg3Lbl.setText("");
    }//GEN-LAST:event_GroupIDfieldKeyReleased

    private void generateIDbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateIDbtnActionPerformed

        if(AYSfield.getSelectedItem().toString().isEmpty() ||  Programmefield.getSelectedItem().toString().isEmpty() ||  GroupNoField.getText().trim().isEmpty() ||  SubGroupNoField.getText().trim().isEmpty()){
            EmptyMsg3Lbl.setText("Please fill all the details ");
        }
        else{
            GroupIDfield.setText(AYSfield.getSelectedItem()+ "." + Programmefield.getSelectedItem() + "." + GroupNoField.getText());
            SubGroupIDfield.setText(AYSfield.getSelectedItem()+ "." + Programmefield.getSelectedItem() + "." + GroupNoField.getText() + "." + SubGroupNoField.getText());

            EmptyMsg3Lbl.setText("");
        }
    }//GEN-LAST:event_generateIDbtnActionPerformed

    private void EditAYSfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditAYSfieldKeyReleased
        EmptyMsg4Lbl.setText("");
    }//GEN-LAST:event_EditAYSfieldKeyReleased

    private void EditProgrammeFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditProgrammeFieldKeyReleased
        EmptyMsg4Lbl.setText("");
    }//GEN-LAST:event_EditProgrammeFieldKeyReleased

    private void EditGroupNoFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditGroupNoFieldKeyReleased
        EmptyMsg4Lbl.setText("");
        EditGroupIDField.setText("");
        EditSubGroupIDField.setText("");
        errorlabel.setText("");
    }//GEN-LAST:event_EditGroupNoFieldKeyReleased

    private void EditSubGroupNoFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditSubGroupNoFieldKeyReleased
        EmptyMsg4Lbl.setText("");
        EditGroupIDField.setText("");
        EditSubGroupIDField.setText("");
        errorlabel.setText("");
    }//GEN-LAST:event_EditSubGroupNoFieldKeyReleased

    private void EditAYSfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditAYSfieldKeyPressed
        EmptyMsg4Lbl.setText("");
    }//GEN-LAST:event_EditAYSfieldKeyPressed

    private void EditProgrammeFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditProgrammeFieldKeyPressed
        EmptyMsg4Lbl.setText("");
    }//GEN-LAST:event_EditProgrammeFieldKeyPressed

    private void EditAYSfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EditAYSfieldKeyTyped
        EmptyMsg4Lbl.setText("");
    }//GEN-LAST:event_EditAYSfieldKeyTyped

    private void EditProgrammeFieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditProgrammeFieldMouseReleased
        EmptyMsg4Lbl.setText("");
        GroupIDfield.setText("");
        SubGroupIDfield.setText("");
    }//GEN-LAST:event_EditProgrammeFieldMouseReleased

    private void AYSfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AYSfieldMouseClicked
        EmptyMsg3Lbl.setText("");
        GroupIDfield.setText("");
        SubGroupIDfield.setText("");
        GroupIDfield.setEditable(false);
        SubGroupIDfield.setEditable(false);
    }//GEN-LAST:event_AYSfieldMouseClicked

    private void ProgrammefieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProgrammefieldMouseClicked
        EmptyMsg3Lbl.setText("");
        GroupIDfield.setText("");
        SubGroupIDfield.setText("");
    }//GEN-LAST:event_ProgrammefieldMouseClicked

    private void EditAYSfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditAYSfieldMouseClicked
       EmptyMsg4Lbl.setText("");
       EditGroupIDField.setText("");
       EditSubGroupIDField.setText("");
       errorlabel.setText("");
    }//GEN-LAST:event_EditAYSfieldMouseClicked

    private void EditProgrammeFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditProgrammeFieldMouseClicked
       EmptyMsg4Lbl.setText("");
       EditGroupIDField.setText("");
       EditSubGroupIDField.setText("");
       errorlabel.setText("");
    }//GEN-LAST:event_EditProgrammeFieldMouseClicked

    private void lectureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lectureActionPerformed
        lecture Lecture = new lecture();
       Lecture.show();
       dispose();
    }//GEN-LAST:event_lectureActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
         int g = JOptionPane.showConfirmDialog(null, "Do you really want to close the application?","Select",JOptionPane.YES_NO_OPTION);
        if(g==0){
            System.exit(0);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void EditGroupIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditGroupIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditGroupIDFieldActionPerformed

    private void StudentIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentIDFieldActionPerformed

    private void GroupIDfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GroupIDfieldActionPerformed
        GroupIDfield.setEditable(false);
    }//GEN-LAST:event_GroupIDfieldActionPerformed

    private void studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentActionPerformed

    private void sessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sessionActionPerformed
        sessions Session = new sessions();
        Session.show();
        dispose();
    }//GEN-LAST:event_sessionActionPerformed

    private void subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectActionPerformed
        // TODO add your handling code here:
        subject Subject = new subject();
       Subject.show();
       dispose();
    }//GEN-LAST:event_subjectActionPerformed

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        // TODO add your handling code here:
        AddLocation locatn = new AddLocation();
        locatn.show();
        dispose();
    }//GEN-LAST:event_locationActionPerformed

    private void statActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statActionPerformed
        // TODO add your handling code here:
        Statistics stats = new Statistics();
        stats.show();
        dispose();
    }//GEN-LAST:event_statActionPerformed

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        // TODO add your handling code here:
        generateTimetable genTime = new generateTimetable();
        genTime.show();
        dispose();
    }//GEN-LAST:event_generateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Students().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AYSerrorLabel;
    private javax.swing.JComboBox<String> AYSfield;
    private javax.swing.JButton AddStudentBtn;
    private javax.swing.JButton Clear;
    private javax.swing.JButton DeleteStudentButton;
    private javax.swing.JComboBox<String> EditAYSfield;
    private javax.swing.JTextField EditGroupIDField;
    private javax.swing.JTextField EditGroupNoField;
    private javax.swing.JComboBox<String> EditProgrammeField;
    private javax.swing.JTextField EditSubGroupIDField;
    private javax.swing.JTextField EditSubGroupNoField;
    private javax.swing.JLabel EmptyMsg3Lbl;
    private javax.swing.JLabel EmptyMsg4Lbl;
    private javax.swing.JTextField GroupIDfield;
    private javax.swing.JTextField GroupNoField;
    private javax.swing.JComboBox<String> Programmefield;
    private javax.swing.JTextField StudentIDField;
    private javax.swing.JTextField SubGroupIDfield;
    private javax.swing.JTextField SubGroupNoField;
    private javax.swing.JButton UpdateStudentButton;
    private javax.swing.JButton WDH;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel contnt;
    private javax.swing.JLabel errorlabel;
    private javax.swing.JButton generate;
    private javax.swing.JButton generateID2;
    private javax.swing.JButton generateIDbtn;
    private javax.swing.JPanel heading;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JButton lecture;
    private javax.swing.JButton location;
    private javax.swing.JPanel logo;
    private javax.swing.JLabel logoLab;
    private javax.swing.JButton logout;
    private javax.swing.JPanel nb;
    private javax.swing.JButton session;
    private javax.swing.JButton stat;
    private javax.swing.JButton student;
    private javax.swing.JTable studentTable;
    private javax.swing.JButton subject;
    private javax.swing.JButton tag;
    // End of variables declaration//GEN-END:variables
}
